<Project Sdk="Dalamud.NET.Sdk/13.0.0">
    <PropertyGroup>
        <Version>2.5.22.1</Version>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <DefineConstants>DEBUG;xREADONLY</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="YamlDotNet" Version="12.3.1" GeneratePathProperty="true"/>
        <None Include="$(PkgYamlDotNet)\lib\net45\YamlDotNet.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="help.yaml"/>
    </ItemGroup>
</Project>
